### ISSUE TITLE
Error when reading FACS data: Can't update the flowFrame because colnames of the input are not consistent with ncdfFlowSet!

### ISSUE THREAD

**Issue by r-cheologist** [RGLab/CytoML#57] opened 2019-05-29 07:16 UTC
After installing like so:

    required_devel_paths <- list(
      c(path = "RGLab/cytolib", branch = "trunk"),
      c(path = "RGLab/flowCore", branch = "trunk"),
      c(path = "RGLab/ncdfFlow", branch = "trunk"),
      c(path = "RGLab/flowWorkspace", branch = "trunk"),
      c(path = "RGLab/openCyto", branch = "trunk"),
      c(path = "RGLab/CytoML", branch = "trunk"))
    for (pt in required_devel_paths) {
      remotes::install_github(repo = pt['path'], ref = pt['branch'])
    }   

I try to use like so:

    library(magrittr)
    xml_path <- "AMS109.xml"
    gs <- CytoML::open_diva_xml(xml_path) %>%
      CytoML::diva_to_gatingset()
    Choose which group of samples to import:
    1: AMS109 1-12
    Selection: 1
    Parsing 13 samples
    All FCS files have the same following channels:
    Time
    FSC-A
    FSC-H
    FSC-W
    SSC-A
    SSC-H
    SSC-W
    FITC-A
    UV450-A
    Alexa Fluor 647-A
    done!
    .............done!
    loading data: ./AMS109 1-12_10_001.fcs
    swap cols: FSC-H:FSC-W
    swap cols: SSC-H:SSC-W
    Compensating
    computing data range
    transforming ...
    parsing gates ...
    Error in .local(x, i, j, ..., value = value) : 
      Can't update the flowFrame because colnames of the input are not consistent with     
    ncdfFlowSet!

What is this newbie doing wrong?

**Comment by mikejiang** [comment] 2019-05-29 17:38
It is caused by the latest change from RGLab/flowCore#153, I've pushed the fix to `CytoML` and give it another try.

**Comment by r-cheologist** [comment] 2019-05-30 13:45
After pulling that fix, I indeed can load the work space with above coade, BUT now I'm faced with the following error trying to access it:

    > library(flowWorkspace)
    > plot(gs)
    Error in text.default(labelX, labelY, label, col = textCol, cex = cex *  : 
      no coordinates were supplied

The same happens for `plot(gs[[1]])`... how to proceed?

**Comment by mikejiang** [comment] 2019-05-30 16:59
what's the output of `gs_get_pop_paths(gs)`? and `traceback()` for that error

**Comment by r-cheologist** [comment] 2019-05-30 17:41
> gs_get_pop_paths(gs)
    [1] "root"

    > plot(gs)
    Error in text.default(labelX, labelY, label, col = textCol, cex = cex *  : 
      no coordinates were supplied
    > traceback()
    8: text.default(labelX, labelY, label, col = textCol, cex = cex * 
           as.numeric(fontsize)/14)
    7: text(labelX, labelY, label, col = textCol, cex = cex * as.numeric(fontsize)/14)
    6: drawEdges(x)
    5: .local(x, ...)
    4: renderGraph(lay)
    3: renderGraph(lay)
    2: plot(gs)
    1: plot(gs)

I interpret this as no gates imported...!? Visual inspection of the `XML`in question appears to have gates defined ...

**Comment by mikejiang** [comment] 2019-05-30 18:01
You may need to set `worksheet` argument properly, see https://github.com/RGLab/CytoML/issues/10#issuecomment-435219820

**Comment by r-cheologist** [comment] 2019-05-30 19:17
That seems to get me started indeed. Thank you very much!

**Closed** 2019-05-30 19:18 UTC
