### ISSUE TITLE
gatingset_to_flowjo docker error

### ISSUE THREAD

**Issue by alexheubeck** [RGLab/CytoML#97] opened 2020-05-21 06:49 UTC
Hi,

I just pulled the recent update, and ran into this error with gatingset_to_flowjo:

```
> outFile <- tempfile(fileext = ".wsp")
> gatingset_to_flowjo(gs, outFile)
Error in gatingset_to_flowjo(gs, outFile) : 
  'docker' command is not found! 
```

Just looking for some guidance for getting this function working, thanks! 
Here's my session info: 

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] devtools_2.3.0            usethis_1.6.1             BiocManager_1.30.10      
 [4] knitr_1.28                gridExtra_2.3             colorRamps_2.3           
 [7] scales_1.1.1              CytoML_2.1.0              tibble_3.0.1             
[10] data.table_1.12.8         ggcyto_1.17.0             ggplot2_3.3.0            
[13] ncdfFlow_2.35.0           BH_1.72.0-3               RcppArmadillo_0.9.880.1.0
[16] flowCore_2.1.0            flowWorkspace_4.1.1       openCyto_2.1.0                  

```

**Comment by jacobpwagner** [comment] 2020-05-21 08:54
`gatingset_to_flowjo` is now pre-compiled and available via a docker image for those users who need it. See here: 
https://hub.docker.com/r/wjiang2/gs-to-flowjo

It will also likely very soon be moved to the `rglab` Docker Hub account and so have that URL switched to: 
https://hub.docker.com/r/rglab/gs-to-flowjo

Anyway, first you'll need to install Docker if you don't already have it: 
https://docs.docker.com/get-docker/

Then pull the image:
```
docker pull wjiang2/gs-to-flowjo
```
`gatingset_to_flowjo` handles running the container, so you should be able to make your calls from `CytoML` as before.

**Comment by alexheubeck** [comment] 2020-05-22 00:49
Thanks Jacob, that's what I figured but I wanted to make sure I did it correctly. It might be nice to include the docker install instruction somewhere (or maybe I just missed it...)

This is the error I'm getting now:

```
outFile <- paste(fcsfilename, ".wsp", sep="")
gatingset_to_flowjo(gs, outFile)

Error in gatingset_to_flowjo(gs, outFile) : docker: invalid reference format: repository name must be lowercase.See 'docker run --help'.
```

**Comment by jacobpwagner** [comment] 2020-05-22 01:07
Hi Alex. I just updated this (https://github.com/RGLab/CytoML/commit/4bb7987a9faf6726baa957c217a004cadf993446), in part to reflect the fact that the image moved to here: https://hub.docker.com/r/rglab/gs-to-flowjo. Can you please try:
1) Pulling those most recent changes
2) `docker pull rglab/gs-to-flowjo`

And then try again. Let me know if you still run in to an error.

**Comment by alexheubeck** [comment] 2020-05-22 18:32
Getting the same error. 

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] knitr_1.28                gridExtra_2.3             colorRamps_2.3            scales_1.1.1              CytoML_2.1.0              tibble_3.0.1              data.table_1.12.8        
 [8] ggcyto_1.17.0             ggplot2_3.3.0             ncdfFlow_2.35.0           BH_1.72.0-3               RcppArmadillo_0.9.880.1.0 flowCore_2.1.0            flowWorkspace_4.1.1      
[15] openCyto_2.1.0   
```

**Comment by jacobpwagner** [comment] 2020-05-22 20:10
`CytoML` is currently at 2.1.1:
https://github.com/RGLab/CytoML/blob/b7b45068c825fb924c514e6b14b824a159d3afc4/DESCRIPTION#L4
 while your session info shows 2.1.0 so you couldn't have updated it to grab those changes. Please update `CytoML` from GitHub. You can just use `remotes::install_github("RGLab/CytoML")`

**Comment by alexheubeck** [comment] 2020-05-22 21:27
Sorry, I was trying update from Bioc instead of the github repo.

Here is the error I'm getting now: 

```
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DROUT -I../inst/include/ -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -ftemplate-depth=900 -DBOOST_NO_AUTO_PTR  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RProtoBufLib/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cytolib/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rhdf5lib/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/flowWorkspace/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/CytoML.h:5:
In file included from ../inst/include/CytoML/openWorkspace.hpp:11:
In file included from ../inst/include/CytoML/macFlowJoWorkspace.hpp:10:
../inst/include/CytoML/flowJoWorkspace.hpp:387:9: error: no matching member function for call to 'gating'
                                gh->gating(fr, 0,false, config_const.compute_leaf_bool_node, config_const.skip_faulty_node);
                                ~~~~^~~~~~
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cytolib/include/cytolib/GatingHierarchy.hpp:231:7: note: candidate function not viable: no known conversion from 'const bool' to 'cytolib::INTINDICES &' for 5th argument
        void gating(MemCytoFrame & cytoframe, VertexID u,bool recompute
             ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cytolib/include/cytolib/GatingHierarchy.hpp:230:7: note: candidate function not viable: requires at most 4 arguments, but 5 were provided
        void gating(MemCytoFrame & cytoframe, VertexID u,bool recompute=false, bool computeTerminalBool=true);
             ^
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/CytoML.h:5:
In file included from ../inst/include/CytoML/openWorkspace.hpp:12:
../inst/include/CytoML/winFlowJoWorkspace.hpp:439:30: warning: '/*' within block comment [-Wcomment]
           * "*[local-name()='edge']/*[local-name()='vertex']" is for ellipsoidGate
                                    ^
1 warning and 1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘CytoML’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CytoML’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CytoML’
Error: Failed to install 'CytoML' from GitHub:
  (converted from warning) installation of package ‘/var/folders/kw/zklp5xq12wbfxlr5npt8l1mmbly_fr/T//RtmpW2h6ba/filebb5b32b2eb0/CytoML_2.1.1.tar.gz’ had non-zero exit status
```

Not sure if this is something I did wrong on my end or not, thanks again for your help.

**Comment by jacobpwagner** [comment] 2020-05-22 21:50
Interesting. I know the cause, which is that your `cytolib` version is a little behind the `CytoML` version and so doesn't have this commit:
https://github.com/RGLab/cytolib/commit/d02503918cc751c5435b4e5861060dcfc673b737
But it's strange that the installation didn't complain about the version discrepancy because there was a bump immediately following that:
https://github.com/RGLab/cytolib/commit/ee6bb4bfe10e90796367002d165ab9711fdf2463
And it should be enforced by the accompanying bump in the requirement from `CytoML`:
https://github.com/RGLab/CytoML/commit/6eb3cfef445aaa4a8d6922649516950ccebe16a5#diff-35ba4a2677442e210c23a00a5601aba3

Point being, you should be getting an error telling you to update `cytolib` rather than letting it get all the way to a compilation error. Anyway, first, could you let me know your cytolib package version just so I can verify the cause:
```
packageVersion("cytolib")
```
Then, if you are going to be working with the most GitHub development versions (as opposed to Bioconductor 3.11), reinstall `cytolib` and its dependent packages:
```
remotes::install_github("RGLab/cytolib")
remotes::install_github("RGLab/flowCore") # Probably not necessary, but just being safe
remotes::install_github("RGLab/flowWorkspace")
remotes::install_github("RGLab/CytoML")
```

**Comment by alexheubeck** [comment] 2020-05-22 22:24
OK, heres where I'm at now: 

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] cytolib_2.1.4             knitr_1.28                gridExtra_2.3            
 [4] colorRamps_2.3            scales_1.1.1              CytoML_2.1.1             
 [7] tibble_3.0.1              data.table_1.12.8         ggcyto_1.17.0            
[10] ggplot2_3.3.0             ncdfFlow_2.35.0           BH_1.72.0-3              
[13] RcppArmadillo_0.9.880.1.0 flowCore_2.1.0            flowWorkspace_4.1.2      
[16] openCyto_2.1.0           
```

So when I run gatingset_to_flowjo with the working directory set to /User/alex.heubeck, I get a TextEdit file that is generated by cytoML.

If the directory is set anywhere else, I get the same error: 
```
Error in gatingset_to_flowjo(gs, outFile) : 
  docker: invalid reference format: repository name must be lowercase.See 'docker run --help'.
```
I'm just looking to get the .wsp file into a specific folder.

**Comment by jacobpwagner** [comment] 2020-05-22 22:41
That's really strange. I can do that on my end with no issue (it's how I've been testing it for the most part actually). For `outFile`, I've tried using absolute paths as well as relative paths based on various working directories and all complete successfully. Could you give me a case of a working directory and `outFile` combination that results in this?

**Comment by jacobpwagner** [comment] 2020-05-23 00:14
I've been testing in Linux, but I also just tested on Windows 10 in R 4.0 with a fresh installation of all of the packages from GitHub and all seems to work as expected. I can write workspace files out to various locations based on absolute paths and relative paths from various working directories without issue.

I'll keep looking for any potential package version mismatches, but this could also be an issue with pathing or permissions for R under macOS Catalina, as I believe there may have been some similar issues with Catalina for other packages.

**Comment by alexheubeck** [comment] 2020-05-23 00:32
Ok, I think I figured something out.

So when I run this: 

```
> gs
A GatingSet with 1 samples
> getwd()
[1] "/Users/alex.heubeck"
> outFile <- paste("gs_to_wsp",fileext = ".wsp",sep="")
> outFile
[1] "gs_to_wsp.wsp"
> gatingset_to_flowjo(gs, outFile)
```

I get a TextEdit file in that location that has the code for the workspace, but not the actual workspace file.

When I set it to save to the Documents folder one level down: 
```
> gs
A GatingSet with 1 samples
> setwd('/Users/alex.heubeck/Documents')
> getwd()
[1] "/Users/alex.heubeck/Documents"
> outFile <- paste("gs_to_wsp",fileext = ".wsp",sep="")
> outFile
[1] "gs_to_wsp.wsp"
> gatingset_to_flowjo(gs, outFile)
```
Docker asked for permissions to that folder, and I got the correct .wsp file. 

When I set it so save into the next folder down that has a space in the name: 

```
> gs
A GatingSet with 1 samples
> setwd('/Users/alex.heubeck/Documents/Automated Analysis')
> getwd()
[1] "/Users/alex.heubeck/Documents/Automated Analysis"
> outFile <- paste("gs_to_wsp",fileext = ".wsp",sep="")
> outFile
[1] "gs_to_wsp.wsp"
> gatingset_to_flowjo(gs, outFile)
Error in gatingset_to_flowjo(gs, outFile) : 
  docker: invalid reference format.See 'docker run --help'.
```
I get the same error. So maybe it has something to do with the spaces in the filepath?

**Comment by jacobpwagner** [comment] 2020-05-23 00:56
Ah. Yeah, it is probably the space in the path not being handled so the command sees it as two distinct tokens. I'll get on a workaround fix for that. 

To your first point, when you say it has the "code for the workspace" but not the "actual workspace file", what exactly do you mean? The method will write out XML in the FlowJo Workspace format. That may be what you mean by "code for the workspace". As far as your computer recognizing it as a workspace file to be opened by FlowJo, that's a matter of setting the default program for the `.wsp` extension. That may differ based on file path depending on how your preferences are set up, which may explain why it looks like a different file type depending on which directory it's saved in.

So, for that file that looks like a TextEdit file. Does it still have the `.wsp` extension (so, it is called `gs_to_wsp.wsp`)? And if you try opening it from FlowJo, does it work as well as `gs_to_wsp.wsp` saved in the other location?

**Comment by jacobpwagner** [comment] 2020-05-23 01:17
Also, regarding the space issue, for now you can get around it by specifying an absolute path and escaping the spaces yourself:
```
outFile <- /Users/alex.heubeck/Documents/Automated\\ Analysis/gs_to_wsp.wsp
``` 
But I'll have a fix up pretty soon, so you could also just wait for me to add to logic to escape the spaces for you.

**Comment by jacobpwagner** [comment] 2020-05-23 01:51
Okay, should be fixed by this commit: https://github.com/RGLab/CytoML/commit/35927af373b656b95442315e505594cff4818386 . Due to the logic I just added to match docker image tag to `cytolib` version (https://github.com/RGLab/CytoML/commit/d126c7814f775bc83487ec6d135a77b4d31827bc), you should get rid of the "latest" tagged docker image and switch to "devel". Removing the "latest" tagged image isn't necessary. It will just free up wasted space.

So, first run this in R:
```
remotes::install_github("RGLab/CytoML")
```
Then run these lines in a terminal:
```
docker rmi -f rglab/gs-to-flowjo:latest
docker pull rglab/gs-to-flowjo:devel
```
Then you should be good to go again and you won't need to manually escape any spaces. Sorry for the hassle. You just happen to be working with the development version of this right as we are making some pretty substantive changes.

**Comment by alexheubeck** [comment] 2020-05-26 16:09
Hey Jacob,

Thanks for all your help with this, it's working appropriately now, so you can close the ticket. 

In response to the question about the TextEdit file, that file does not have the .wsp extension on it from some reason, but only if I was saving in /Users/alex.heubeck directly. When I set it to save in /Users/alex.heubeck/Documents, it saved as a .wsp.

**Comment by jacobpwagner** [comment] 2020-05-26 16:50
Yeah, that last point sounds a little more like an issue of default display/lack of display of extension for your home directory, or possibly default extension truncation behavior for the home directory, but that's weirder. I've checked that periods in the file path aren't disrupting anything with regards to saving the file out. I'll go ahead and close this, but let me know if anything else comes up and I can re-open it.

**Closed by jacobpwagner** 2020-05-26 16:50 UTC
